[package]
name = "holiday"
version = "0.1.0"
authors = ["Ryan O'Beirne <ryanobeirne@ryanobeirne.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"

[dev-dependencies]
two_timer = "2.1.0"
